# Generated by Django 5.2.1 on 2025-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('Name', models.TextField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
    ]
