# Generated by Django 5.2.1 on 2025-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
