# Generated by Django 5.2.1 on 2025-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fooditem_delete_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='samplestudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
